# Site settings
title: kara woo
email: woo.kara@gmail.com
author: Kara Woo
description: "Lake Baikal, data management, open science, social justice"
baseurl: ""
url: "http://karawoo.github.io"
google_analytics:
animated: false
show_related_posts: false
timezone: America/Los_Angeles

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
paginate: 5
sass:
  compressed: true
